### ISSUE TITLE
Support for react native web

### ISSUE THREAD

**Issue by rlindskog** [computerjazz/react-native-draggable-flatlist#133]
*✅I have completed ALL installation steps.*

**Describe the bug**
Trying to use with [react-native-web](https://github.com/necolas/react-native-web), not sure if this package is supported for web so this might be a feature request.

**To Reproduce**
`import DraggableFlatList from 'react-native-draggable-flatlist'`

**Platform & Dependencies**
Please list any  applicable dependencies in addition to those below (react-navigation etc).
 - Platform: web
 - React Native version: ^0.60.5
 - React Native web version: ^0.11.7
 - Reanimated version: ^1.7.0
 - React Native Gesture Handler version: ^1.5.3

**Additional context**
Getting this error
```
Failed to compile.

./node_modules/react-native-draggable-flatlist/index.tsx 69:5
Module parse failed: Unexpected token (69:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> type AnimatedFlatListType<T> = { getNode: () => RNFlatList<T> };
| 
| export type DragEndParams<T> = {
```

**Comment by computerjazz** [comment]
Looks like you're not running typescript? I just changed the export to be js in the latest release so you should no longer get that error. That said I've never tested web and would be a little surprised if it works. Please let me know how it goes!

**Comment by curiousdustin** [comment]
I tested this briefly. Ran into errors related to `react-native-reanimated` and `react-native-gesture-handler`.

```
ncaught TypeError: Cannot read property 'configureProps' of undefined
    at configureProps (ConfigHelper.js:107)
    at Object../node_modules/react-native-reanimated/src/ConfigHelper.js (ConfigHelper.js:126)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object../node_modules/react-native-reanimated/src/Animated.js (Animated.js:25)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
    at Object../node_modules/react-native-draggable-flatlist/lib/index.js (index.js:76)
    at __webpack_require__ (bootstrap:723)
    at fn (bootstrap:100)
```
If I mock `react-native-reanimated` to use `Animated` from `react-native` instead, I get this error:
```
invariant.js:40 Uncaught Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.
    at invariant (https://player.curiousmedia.com:8080/bundle.js:118681:810)
    at Object.createAnimatedComponent (https://player.curiousmedia.com:8080/bundle.js:118130:1813)
    at Object../node_modules/react-native-draggable-flatlist/lib/index.js 
```

**Comment by computerjazz** [comment]
`Animated` is pretty different from `react-native-reanimated`, I'd be surprised if that worked.

There isn't much in the docs, but both Reanimated and RNGH seem to have partial web support as of recently:
https://github.com/software-mansion/react-native-gesture-handler/pull/555
https://github.com/software-mansion/react-native-reanimated/pull/390

**Comment by robertherber** [comment]
I'm also running into issues with web - running react-native-web through expo and getting the following:
```
Uncaught TypeError: 'set' on proxy: trap returned falsish for property '__val'
    at nodify (bundle.js:57680)
    at adapt (bundle.js:57692)
    at createAnimatedSet (bundle.js:59502)
    at nativeEvent (bundle.js:49646)
    at sanitizeArgMapping (bundle.js:58546)
    at new AnimatedEvent (bundle.js:58566)
    at createAnimatedEvent (bundle.js:58647)
    at new DraggableFlatList (bundle.js:49643)
    at constructClassInstance (bundle.js:36705)
    at updateClassComponent (bundle.js:40382)
    at beginWork$1 (bundle.js:41902)
    at HTMLUnknownElement.callCallback (bundle.js:23744)
    at Object.invokeGuardedCallbackDev (bundle.js:23794)
    at invokeGuardedCallback (bundle.js:23851)
    at beginWork$$1 (bundle.js:46614)
    at performUnitOfWork (bundle.js:45605)
    at workLoopSync (bundle.js:45582)
    at renderRoot (bundle.js:45275)
    at runRootCallback (bundle.js:44951)
    at bundle.js:34750
    at unstable_runWithPriority (bundle.js:88846)
    at runWithPriority$2 (bundle.js:34702)
    at flushSyncCallbackQueueImpl (bundle.js:34746)
    at flushSyncCallbackQueue (bundle.js:34735)
    at scheduleUpdateOnFiber (bundle.js:44828)
    at dispatchAction (bundle.js:39213)
    at bundle.js:91676```

Haven't really had time to look into it further.

**Comment by Krzychu81** [comment]
Getting the same error as @robertherber - using expo and `expo start --web`. It works on Android.

**Comment by ianmartorell** [comment]
I created a blank Expo project and copy pasted the example, and it runs without any errors. The functionality seems to be broken though. Long-pressing an item moves it to the top of the list and locks it in the dragging state even if the finger is released, blocking interaction with other items too. Any idea how to go about fixing it? [Here's the repo](http://github.com/ianmartorell/react-native-draggable-flatlist-example).

![ezgif-3-a760f63fc90e](https://user-images.githubusercontent.com/318800/78649932-77f6be00-78be-11ea-9819-5dc185aeaeb7.gif)

I'm also thinking the dragging functionality should work differently when tapping on a touchscreen and dragging with a mouse (don't need to wait for a longpress with a mouse), but I'm not sure if that's even possible to achieve with RNGH.

**Comment by tettoffensive** [comment]
Sounds like this currently doesn't work for react-native-web. Anyone know a good alternative for now?

**Comment by robertherber** [comment]
I've managed to get it moving on the web now. Essentially events triggered by react-native-gesture-handler are a bit different on the web, so the onPanGestureEvent needs to listen for `GestureState.BEGAN` as well:
```TypeScript
onPanGestureEvent = event([
    {
      nativeEvent: ({ x, y }: PanGestureHandlerEventExtra) => cond(
        and(
          this.isHovering,
          Platform.OS === 'web' ? or( // <----------------------- here
            eq(this.panGestureState, GestureState.BEGAN),
            eq(this.panGestureState, GestureState.ACTIVE),
          ) : eq(this.panGestureState, GestureState.ACTIVE),
          not(this.disabled),
        ),
        [
          cond(not(this.hasMoved), set(this.hasMoved, 1)),
          set(
            this.touchAbsolute,
            add(this.props.horizontal ? x : y, this.activationDistance),
          ),
        ],
      ),
    },
  ]);
```

There are some quirks that needs more work for this to be fully useable, maybe someone can spot quick solutions for these?
- The position before dragging is still at the top of the list
- The drop position is sometimes off (less
- Sometimes it doesn't manage to end the drag but gets stuck

I feel this issue (at least the part I marked out involving states) would best be solved in react-native-gesture-handler in the long term - but I guess it might require [replacing hammerjs](https://github.com/software-mansion/react-native-gesture-handler/issues/902) which might be easier said than done. So if we could just solve it here for now it'd be great :)

**Comment by sreuter** [comment]
@robertherber Awesome stuff. I'm keen to get this working on web as well. Did you already have have a discussion with the react-native-gesture-handler maintainers about this as well?

**Comment by robertherber** [comment]
@sreuter I haven’t had time to pursue this further :(

**Comment by robertherber** [comment]
@computerjazz Just tried and web seems to work well in master now. New npm release please? 🙏😁

**Comment by robertherber** [comment]
It seems to be working fairly well on web now. The issue that remains seems to be when there's a scroll offset - which makes it bug out.

**Comment by computerjazz** [comment]
yeah so the issue on web is that `onScroll` doesn't seem to ever trigger, so the `scrollOffset` doesn't get updated. I'm guessing this is due to the scrolling div not being the flatlist div, but I haven't dug in too deep.

**Comment by SrBrahma** [comment]
Any news?

**Comment by cannse** [comment]
In case this is helpful to anyone else who stumbles upon this thread:

Version `3.1.1` was working well for me on web, but started causing issues on Android. Version `4.0.1` works well for Android, but started throwing errors on web.

I finally solved this by using separate versions for web vs. mobile:

`package.json`
-
```
{
  ...
  "dependencies": {
    ...
    "react-native-draggable-flatlist": "^4.0.1",
    "react-native-draggable-flatlist-web": "npm:react-native-draggable-flatlist@3.1.1",
    ...
  }
}
```

`DraggableList.js`
-
```
import React from "react";
import DraggableFlatList from "react-native-draggable-flatlist-web";

export default function DraggableList(props) {
  return <DraggableFlatList {...props} />;
}
```

`DraggableList.native.js`
-
```
import React from "react";
import DraggableFlatList from "react-native-draggable-flatlist";

export default function DraggableList(props) {
  return <DraggableFlatList {...props} />;
}
```

**Comment by cannse** [comment]
@hannah-jemima (and anyone else on this thread)—I recently upgraded to the latest version of Expo and I've also been running into issues with `react-native-reanimated` versions in my original implementation. It's possible there's a workaround, but I ended up just implementing `react-beautiful-dnd` for the web version of my `DraggableList` component. This seems to also improve the experience on web and reduce some of the glitches with the `react-native-draggable-flatlist` on web, like the ones you mentioned. `react-beautiful-dnd` is working well for me, but there are lots of other drag-and-drop packages built for React that could probably work just as well.

So here's my new implementation that seems to work well:

## `package.json`
```
{
  ...
  "dependencies": {
    ...
    "react-beautiful-dnd": "^13.1.1",
    "react-native-draggable-flatlist": "^4.0.1",
    ...
  }
}
```

## `DraggableList.js`
```
import React from "react";
import { DragDropContext, Droppable, Draggable } from "react-beautiful-dnd";

export default function DraggableList(props) {
  const { data, onDragEnd, renderItem } = props;
  return (
    <DragDropContext
      onDragEnd={(result) => {
        if (!result.destination) return;
        const newData = Array.from(data);
        const [removed] = newData.splice(result.source.index, 1);
        newData.splice(result.destination.index, 0, removed);
        onDragEnd({ data: newData });
      }}
    >
      <Droppable droppableId="droppable">
        ...etc., based on https://www.npmjs.com/package/react-beautiful-dnd
      </Droppable>
    </DragDropContext>
  );
}
```

## `DraggableList.native.js`
```
import React from "react";
import DraggableFlatList from "react-native-draggable-flatlist";

export default function DraggableList(props) {
  return <DraggableFlatList {...props} />;
}
```

**Comment by hannah-jemima** [comment]
@cannse finally got round to having another go at this and it worked! Thank you so much for sharing. Plugging in `react-beautiful-dnd` was my first port of call because I use that in my desktop browser app already so I'm familiar with it. Then ran into errors so I gave up. But knowing you were able to get it working gave me the confidence to try again. Didn't manage to set the `provided.innerRef` on a `View` but it did let me wrap it in a `<div>` so I could set the ref there.
