### ISSUE TITLE
undefined is not an object (evaluating 'p.height') Android

### ISSUE THREAD

**Issue by eminsr** [computerjazz/react-native-draggable-flatlist#28]
After rearranging a couple of items, sometimes the app crashes with the following error.

Android Version: 6.0

```
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.example, PID: 13113
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'p.height'), stack:
    onPanResponderRelease@597:6166
    S@262:2929
    onResponderRelease@262:2858
    g@66:551
    S@66:694
    P@66:748
    z@66:1913
    j@66:2675
    D@66:2472
    <unknown>@66:14047
    Ie@66:70003
    Me@66:13717
    De@66:13890
    receiveTouches@66:14710
    value@18:3477
    <unknown>@18:959
    value@18:2721
    value@18:931
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:148)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by rom1k** [comment]
Also getting a crash in production, I think it might be related to this plugin

```
com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'c.height'), stack:
onPanResponderRelease@1306:6118
S@291:2929
onResponderRelease@291:2858
y@90:576
k@90:719
P@90:773
D@90:1940
F@90:2699
W@90:2499
<unknown>@90:13491
Ae@90:74434
ze@90:13161
Me@90:13334
receiveTouches@90:14154
value@37:3449
<unknown>@37:960
value@37:2703
value@37:932
at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java
  at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException (ExceptionsManagerModule.java:38)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:160)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loop (Looper.java:193)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:192)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by barneysbro** [comment]
@eminsr  I'm facing the same problem. Can you share more detail about the activeMeasurements? How do you finally fix this value undefined issue?
